### ISSUE TITLE
ai-complete-code-at-point tries to use OpenAI instead of HF

### ISSUE THREAD

**Issue by gdindi** [ai-mode/ai-mode-hf#1]
Hi,

First of all, thanks for this work.

I have installed both ai-mode and ai-mode-hf. I have configured `ai-completions--backends` to contain only  `(("HuggingFace" . ai-mode-hf--completion-backend))`. However, when calling  `ai-complete-code-at-point`, I get this error:

`error in process filter: Error while parsing response body: You didn’t provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you’re accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.`

I have found that I need to manually call `ai-completions-change-backend` manually.

Also, once the backend is correctly set, I get the following error:

```
Sending POST request[b4f11e70-9ebc-4572-90e5-19b3d5901030] to ’https://api-inference.huggingface.co/models/bigcode/starcoder
Contacting host: api-inference.huggingface.co:443
error in process filter: ai-utils--log-and-error: Error while parsing response body: Wrong type argument: plistp, (error . "Input validation error: ‘top_p‘ must be > 0.0 and < 1.0")
error in process filter: Error while parsing response body: Wrong type argument: plistp, (error . "Input validation error: ‘top_p‘ must be > 0.0 and < 1.0")
```

So I manually set `ai-mode-hf--model-temperature`  to 1.

Now it works.

Thanks!

**Comment by Lispython** [comment]
Hi, @gdindi 

Thank you for your feedback. I have updated the README with instructions on how to change the default backend.

Regarding the issue with the incorrect value of top_p. I have realized that I had already resolved this issue in my local codebase, but had not yet pushed the changes to the repository. Thank you for bringing this to my attention. 

With updated code you can reset variable `ai-mode-hf--model-temperature` to defaults.

**Comment by Lispython** [comment]
Can you share some feedback about ai-mode? Have you tried other AI-mode features?

**Comment by gdindi** [comment]
Hi,
Thanks for the reactivity.
I have only used `ai-complet-code-at-point`, which works fine with HuggingFace.
I am just playing around. 
I will report if I find the time to use it a bit.
Thanks again.
